import { chromium } from 'playwright-core';
const browser = await chromium.launch({ executablePath: process.env.CHROME_PATH });
const ctx = await browser.newContext({ viewport: { width: 1440, height: 900 } });
const page = await ctx.newPage();
await page.goto('http://127.0.0.1:8000/shop/product/STLPEN0000007QR?_=' + Date.now(), { waitUntil: 'networkidle' });
await page.waitForTimeout(2500);
await page.click('[data-testid="add-to-cart"]');
await page.waitForTimeout(2000);
await page.goto('http://127.0.0.1:8000/cart?_=' + Date.now(), { waitUntil: 'networkidle' });
await page.waitForTimeout(2500);
await page.screenshot({ path: '/home/bahamut/20feet/_workspace/20ft/visual-pass2/desktop-cart-filled.png', fullPage: true });
console.log('done');
await browser.close();
